# Generated by Django 5.0.6 on 2026-06-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_hash_existing_login_passwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qr_scanner_login',
            options={
                'verbose_name': 'Gas Cylinder Scanner Login',
                'verbose_name_plural': 'Gas Cylinder Scanner Logins',
            },
        ),
    ]
